package com.sl;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
public class HelloController {

	@GetMapping("/hello")
	@ResponseBody // controller generates the response and returns it to the caller(web client)
	public String hello() {
		// any business logic we want to
		
		return "Hello World";
	}

	// This mapping method does not have @ResponseBody annotation
	// which means the response will generated by a "View" 
	@GetMapping("/hello-view")	
	public String helloFromView() {
		// any business logic we want to
		
		return "hello-vw"; // hello-vw will mapped to the WEB-INF/views/hello-vw.jsp
	}
}
