package com.sl;

import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
public class HelloController {

	@GetMapping("/hello")
	@ResponseBody // controller generates the response and returns it to the caller(web client)
	public String hello() {
		// any business logic we want to

		return "Hello World";
	}

	// This mapping method does not have @ResponseBody annotation
	// which means the response will generated by a "View"
	@GetMapping("/hello-view")
	public String helloFromView() {
		// any business logic we want to

		return "hello-vw"; // hello-vw will resolve to the WEB-INF/views/hello-vw.jsp
	}

	// demo using a model (that stores data)
	@GetMapping("/hello-view-model")
	public String helloFromViewWithAModel(ModelMap model) {
		// any business logic we want to

		model.addAttribute("name", "Rudra");
		model.addAttribute("age", 25);

		return "hello-vw-model"; // hello-vw will resolve to the WEB-INF/views/hello-vw-model.jsp
	}

	// regex path pattern
	@GetMapping("/{name:[a-z-]+}-{ipAddress:\\d+\\.\\d+\\.\\d+\\.\\d+}")
	@ResponseBody
	public String handle(@PathVariable("name") String name, @PathVariable("ipAddress") String ipAddress) {
		return "<V2> name:" + name + " ip address " + ipAddress;
	}

}
