spring.application.name=spring-cloud-config-server

server.port=8888

# Location of configuration files
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:///D:/GIT/SL/test-nov-27-25/PHASE3/SPRING-CLOUD-CIS-26-PROJECT-CONFIG